### ISSUE TITLE
Is QCropper compatible for adding rotation gesture to rotate the image using fingers instead of buttons?

### ISSUE THREAD

**Issue by sivaprasadkv** [qchenqizhi/QCropper#10]
Great work!! 
QCropper is almost similar to Photos.app, works well. 
In addition to all these features, I need a rotation gesture to rotate the image using 2 fingers. Could you please let me know whether this iOS framework supports? 
Kindly suggest the required changes in the source code. 

Thanks in advance. 
Siva Prasad K V

**Comment by qchenqizhi** [comment]
I won't add this feature to `Qcropper `(Photos.app doesn't have this either), but you can add it to your own project, you can look at `setStraightenAngle(_:)` of `Rotatable`, all you need to do is added the rotation gesture to an appropriate view, then calculate the angle of rotation and synced to the `AngleRuler` if needed.
