### ISSUE TITLE
How can I crop the image using CIImage

### ISSUE THREAD

**Issue by sweetcodestar** [qchenqizhi/QCropper#11]
This is great source code to crop the image.
Do you have any idea to crop the final image using CIImage? I'd like to apply CIFilter and crop the image.

**Comment by qchenqizhi** [comment]
The cropping operation is mainly based on CGImage, I think it is better that you do another conversion between cropping and CIFiler.

**Comment by sweetcodestar** [comment]
Ok, thank you.
