### ISSUE TITLE
Image with Clear Background results in Black Image

### ISSUE THREAD

**Issue by sohil-vc** [qchenqizhi/QCropper#2]
I am passing an image with clear background that has been erased and when I am done cropping it's losses it's transparency. Please check the attached images.
Original Image
<img width="410" alt="Screenshot 2020-04-11 at 11 35 06 PM" src="https://user-images.githubusercontent.com/57167319/79051404-b9d08d00-7c4d-11ea-8a80-92949a1de9f6.png">
Result Image
<img width="405" alt="Screenshot 2020-04-11 at 11 35 17 PM" src="https://user-images.githubusercontent.com/57167319/79051417-c48b2200-7c4d-11ea-9513-a90cdf1d4910.png">

**Comment by qchenqizhi** [comment]
I have changed the default background color to clear.
please see this [commit](https://github.com/qchenqizhi/QCropper/commit/214ebc681ad2d67b7b342dc11f90aad8898f632a).
