### ISSUE TITLE
Image flipping

### ISSUE THREAD

**Issue by dev4jam** [qchenqizhi/QCropper#20]
Thanks for the best cropping component out there! I have a question: is there any way to avoid flipping an image itself and work out through view transforms during flipping? I'm working on another level cropping tool that uses metal view (MTKView) and I managed to integrate it inside QCropper. But still struggling with flipping.

**Comment by qchenqizhi** [comment]
I have no idea, maybe try adding a transform?
like this: `view.layer.transform = CGAffineTransform(scaleX: 1, y: -1)`
