### ISSUE TITLE
Quality degrades heavily when an image is cropped

### ISSUE THREAD

**Issue by prat14k** [qchenqizhi/QCropper#22]
@qchenqizhi While cropping an image, the quality / size of the image is downgraded. On cropping, the image size decreases  approximately more than half of its original. 

Any way we can avoid this quality / size downgrade?

**Comment by qchenqizhi** [comment]
Qcroper sets the maximum side length of a generated image. If your project will handle very large images and need to output very large images, you can increase these two parameters:
```
QCropper.Config.croppingImageLongSideMaxSize = 5120
QCropper.Config.croppingImageShortSideMaxSize = 5120
```
