### ISSUE TITLE
如何设置图片的默认剪裁区域？

### ISSUE THREAD

**Issue by DachengWang** [qchenqizhi/QCropper#23]
请问，我在打开剪裁界面时，想设置图片的默认剪裁区域（自动将图片上指定的剪裁区域，缩放至屏幕上合适的尺寸），我应该怎么设置？

**Comment by qchenqizhi** [comment]
你可以看看`setAspectRatio`能不能满足需求，如果不行，就需要你自己去实现了。
具体可以看看`CropperViewController`中的`resetToDefaultLayout`，修改其中的代码，来计算得到一个满足需求的`cropBoxFrame`
