### ISSUE TITLE
How can I get pure cropRect without image like ToCropViewController

### ISSUE THREAD

**Issue by kobunketsu** [qchenqizhi/QCropper#4]
Hi, thank you for writing such a good framework, implementing a system photo crop editor becomes so easy with it now. But I have some problem while using it. It is hard to get a pure cropRect which size is relative to the original image's size. I don't really need the cropped image rendered, only the size matters, but I have no idea how to retrieve it through the method:

> public func cropped(withCropperState cropperState: CropperState) -> UIImage?

Can you give me some hint how to do it?

**Comment by qchenqizhi** [comment]
You can get all the information you need through the `CropperViewControllerDelegate`'s `cropperDidConfirm(_:state:)`.
But you need to calculate it yourself through `CropperState`
