### ISSUE TITLE
I don't find the properties to set aspect ratio like the above image in our lib. Could you help me?

### ISSUE THREAD

**Issue by thuongvanbui39** [qchenqizhi/QCropper#7]
I don't find the properties to set aspect ratio like the above image in our lib. Could you help me?
<img width="603" alt="Screen Shot 2021-04-12 at 09 39 21" src="https://user-images.githubusercontent.com/28839405/114410371-86646d80-9bd5-11eb-9353-f79a70337ad6.png">

**Comment by qchenqizhi** [comment]
This one?
```swift
extension AspectRatioSettable where Self : QCropper.CropperViewController {

    public func setAspectRatio(_ aspectRatio: QCropper.AspectRatio)

    public func setAspectRatioValue(_ aspectRatioValue: CGFloat)
}
```

example:
`cropper.setAspectRatio(.ratio(width: 9, height: 16))`

**Comment by thuongvanbui39** [comment]
yes, I see. but the image is selected auto-zoom to center. I want to turn off the zoom center and aspect to fit the original image.

**Comment by qchenqizhi** [comment]
This is not supported, you can modify the relevant code yourself, this logic is mainly controlled by `scrollViewZoomScaleToBounds`

**Comment by thuongvanbui39** [comment]
Yes. Many thanks for your supported.

**Comment by qchenqizhi** [comment]
You are welcome
